[versions]
coroutines = "1.7.3"
kotlin = "1.9.22"
spotless = "6.25.0"

[libraries]

kotlin_core = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlinx_coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx_coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]

kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
